
/***********************************************************************
*
*             Error defintions for NetBoss programs
*
*  ----------------------------------------------------------------
*
*                    ISC Systems Corporation
*                  Confidential / Proprietary
*   Copyright (C) 1989 by ISC-Bunker Ramo / Unpublished Work
*     For Use by ISC-Bunker Ramo and Authorized Users Only
*                     All rights reserved.
*
**********************************************************************/

#ifndef _NBERRORS_H
#define _NBERRORS_H

#include <errno.h>
//extern int sys_nerr;
//extern char *sys_errlist[];

extern char *swerrormsg(register int);
extern	void	LogMsg();

#define NBMSG(args) LogMsg ##args
#define INFO(args) LogMsg("INFO: "), LogMsg ##args 
#define WARNING(args) LogMsg("WARNING: "), LogMsg ##args
#define ERRORM(args) (LogMsg("ERROR: "), LogMsg ##args)
#define FATAL(args) (LogMsg("FATAL: "), LogMsg ##args , exit(1))
#define ERRTEXT() ((errno>=sys_nerr)?"<No Text>":sys_errlist[errno])

/*************************************************************
*
*  Severity levels of errors.  Used by error() routine.
*
*************************************************************/

#define	ERR_INFO		0		/* error severity levels used in	*/
#define	ERR_WARN		1		/* error routine					*/
#define	ERR_FATAL		2

/**************************************************************
*
*   Errors generated by NetBoss, some to be returned to users.
*
**************************************************************/


/*	  Following are errors related to cbtree interface   */

/*start_errors*/

#define DATA_FILE_EXISTS  -6600		/* Data file create requested, already exists */
#define INDEX_FILE_EXISTS -6601		/* Index file create requested, already exists */
#define NBBTBAD_ARG	   	  -6602		/* Illegal argument in function call */
#define NBBTINIT_ERR	  -6603		/* Error initializing CBTREE  */
#define NBBTOPEN_ERR	  -6604		/* Error opening data file */
#define DATA_FILE_MISSING -6605		/* Data file missing on NBcbinit */
#define INDEX_FILE_MISSING -6606		/* Index file missing on NBcbinit  */
#define NBBTINSERTERR	  -6607		/* cbtree insert returned not-ok */
#define NBBTSEEKVERR	  -6608		/* cbtree error on btseekv function */
#define NBBTDISKWRITERR	  -6609		/* error writing data record on insert */
#define NBBTNOTFND		  -6610		/* record not found on cbtree GETREC */
#define NBBTGETERR		  -6611		/* cbtree error on GETREC operation */
#define NBBTSEEKDATAERR	  -6612		/* error seeking data record on get */
#define NBBTDISKREADERR   -6613		/* error reading data rec on get */
#define NBBTDELETERR	  -6614		/* cbtree delete error occurred */
#define NBBTBADDIR		  -6615		/* can't chdir to specified path */
#define NBBTDUPKEY		  -6616		/* duplicate key on insert */
#define NBBTNONASCIIKEY   -6617		/* non-ASCII data in candidate key field */
#define NBBTFNDERR		  -6618		/* cbtree error on GETPAR or GETFRST  */
#define NBBTHIERR		  -6619		/* error on GETLE for high key */
#define NBBTNXTERR		  -6620		/* error on cbtree GETNXT  */
#define	NBBTKEY2LONG      -6621		/* key field too long */
#define	NBBTBADRE         -6622		/* invalid regular expression */
#define NBBTMALLOC        -6623		/* error from malloc() */
#define ERR_NO_CONTXT     -6624		/* no context established */
#define ERR_CNTX_TOO_BIG  -6625		/* invalid context number */
#define BADMSG			  -6626		/* bad message type (internal error) */
#define	NBCBT_ERROR		  -6627		/* Error from CONMAN cbt interface functn */
#define NBCBT_FATAL       -6628		/* fatal cbt or interface error */
#define NBBTRECDIFF       -6629		/* Merge Records are different */
#define NBDBOPFAILED      -6630		/* nbmrg: Could not open NetBoss database - merge failed */
#define NBOPFAILED        -6631		/* nbmrg: Could not open NetBoss - merge failed */

#define	SPL_NO_TRANS	-6650	/* No transactions in spool file */
#define	SPL_IO			-6651	/* I-O error on spool file */
#define SPL_OPEN		-6657	/* Unable to Open/Create spool file */
#define SPL_SEEK		-6653	/* Error seeking in spool file */
#define SPL_READ		-6654	/* Error reading spool file */
#define SPL_TRUNC		-6655	/* Truncation of spool file failed */

#define	BAD_PARM		-6660	/* bad paramater passed (internal error) */
#define	NO_MEM			-6661	/* malloc() failed */
#define	LNETF_NO		-6662	/* missing logical net ID file */
#define	LNETF_EMPTY		-6663	/* empty logical net ID file */
#define	LNETF_BAD		-6664	/* can't parse logical net ID file */
#define	DNPTAB_NO		-6665	/* missing dnp_table file (NETMGR-compatible) */
#define	NOBOSS			-6666	/* unable to open boss for logical network */
#define	CRTMP			-6667	/* error creating temp file for transfer */
#define	LNETF_CREAT		-6668	/* cannot create logical net ID file */
#define	OPENTMP			-6669	/* error opening temp file for transfer */

#define ILDAT2BIG		-6670	/* Input data field too large */
#define ILDAT2SMALL		-6671	/* Input data length is negative */
#define ILDATNULL		-6672	/* Input data pointer is NULL */
#define ILBADOPEN  		-6673	/* bad open to NetBoss */
#define ILREAD			-6674	/* Bad read from netboss */
#define ILREGEX			-6675	/* Regular expression characters not allowed */
#define ILWRITE			-6676	/* Bad write to netboss */
#define ILNOCNTXT		-6677	/* NEXT must be preceded by successful GET */
#define MSG_UNDELIV		-6678	/* message undeliverable to destination */
#define	ABORTED_TRANSF	-6679	/* error during transfer of database */
#define	ILKEYLEN		-6680	/* Input keylength invalid */
#define ILZAP			-6681	/* Zap command requires at least OWNER field */
#define ILCATEGORY		-6682	/* Data type is not valid type for NetBoss */

/*end_errors*/
#endif /* _NBERRORS_H */
