deletrec: recloc
deletrec: cbuff
cmptnode: broblk
cmptnode: skeynme
cmptnode: pos
cmptnode: lbuff
cmptnode: strsave
cmptnode: lnum
cmptnode: lbuff2
cmptnode: endbrokey
cmptnode: endidxky
cmptnode: popnode
creatbtr: idxname
creatbtr: fbuff
creatbtr: fdidx 15
creatbtr: btbase
creatbtr: fbuff
creatbtr: btidxlen
creatbtr: btinfo
creatbtr: fbuff
creatbtr: btidxlen
creatbtr: ubuff
creatbtr: lbuff
creatbtr: lbuff
btrgets: savskey
btrgets: savskey2
btbinary: fwdpage
btbinary: tmpbuf
btgiver
btgiver: freespcb
btgiver: chrbuf
btgiver: pos
btgiver: lbuff
btrinit: btparms.btr
btrisrt: nuidxblk
btrisrt: newkey
btrisrt: pos
btrisrt: pos
stackop.c: pushing an item onto a FULL stack
cbtree: idxblk
cbtree: rootptr
cbtree: btptr
getfhdr: lbuff
getfhdr
getfhdr
adjstack: stktbl
getbtree.c:getroot():  ptrloc
getbtree.c:getroot(): lbuff
getbtree.c:getidxr(): fbuff
getbtree.c:getidxr():
getbtree.c:getidxr(): fbuff
getbtree.c:getidxr(): skeynme
getbtree.c:getidxr(): lbuff
getbtree.c:getidxr():
getbtree.c:getidxr(): fbuff
getbtree.c:getidxr(): strsave()
cpyrtbro: broblk
cpyrtbro: skeynme
cpyrtbro: endidxky
cpyltbro: broblk
cpyltbro: skynme
cpyltbro: endbroky
putbtree: ptrloc
putbtree: lbuff
putbtree: cbuff
putbtree: recnum
putbtree: cbuff
putbtree: 0L
putbtree: lbuff *
putfhdr: fd
putfhdr: fd
btrinit: need memory for fbuff
btrinit: need memory for btstruct->btkey
stackop.c: poping an item from an EMPTY stack
btrgets.c: need memory for *btidxpp
btrgets.c: need memory for *btidxpp->skeynme
cbtree.c:  need memory for btparmst->btsvkey for GETALL scan
btrgets.c: need memory for btrecnum
btrinit.c: need memory for btkey
btrinit.c: need memory for btrecnum
getbtree.c: getidxr: buffer overrun!
lockunlk.c: lock: error while seeking to lock pos
lockunlk.c: unlock: error while seeking to lock pos
btrinit.c: need memory for btrname
btrinit.c: need memory for idxname
delbtree.c:delbtree():fd
delbtree.c:delbtree():&btinfo
delbtree.c:delnode():idxblkp
creatbtr.c:fdidx
creatbtr.c:&btbase
creatbtr.c:fdidx, btcp->findroot
creatbtr.c:fdidx, &btlink
creatbtr.c:fdidx, btcp->findroot2
creatbtr.c:fdidx, &btlink
creatbtr.c:fdidx, btlink.bl_link
creatbtr.c:fdidx, btlink.bl_link2
creatbtr.c: illegal findroot value
creatbtr.c:fdidx, 0L
updilvl.c:lvlblk
updilvl.c: i >= lvlblk->cellicnt
findroot.c:fd, 1L
findroot.c:&btbase
findroot.c:&btinfo
findroot.c:fd, btinfo.bi_rootp
giveidxr.c:reclen
giveidxr.c:ret_loc
giveidxr.c:chrbuf
btbinary.c:neighbor
getbase.c: fd, btbasep
getbtree.c:getroot():  illegal root pointer ptrloc!
BTVARLEN.C:btgetvar(): bad use block detected
BTVARLEN.C:btdelvar(): sav_p beyond eof!
BTVARLEN.C:btdelvar(): corrupted use_block!
BTVARLEN.C:btsizvar(): ...
BTVARLEN.C:btsizvar(): ....
BTVARLEN.C:writezeroes
BTVARLEN.C:writezeroes
BTVARLEN.C: ...
BTVARLEN.C:read_ub(): ...
BTVARLEN.C:read_ub(): ....
BTVARLEN.C:write_ub(): ...
BTVARLEN.C:write_ub(): ....
INITDAT.C:initdat(): cp
INITDAT.C:initdat(): 0L
INITDAT.C:initdat(): btcp->btvarlen
INITDAT.C:initdat(): SZBLKHDR
INITDAT.C:initdat.c: btcp->btvarlen
GETBTREE:getroot(): Invalid Root Pointer! Rebuild Index
CREATBTR.C: fdidx, SZBLKHDR
CREATBTR.C: fdidx, &btbase
BTRINIT.C: BTPARMS.BTR / Index File Mismatch!
BTCINIT.C: BAD btkeytyp
