extern int comm_to_ascii_enc_hex(char type,char *source,int length,char **dest ,int length_dst,char just,short fill,char *pattern);
extern int comm_from_ascii_enc_hex(char *start_ptr,char type,int length,char *pattern);
extern int comm_to_ascii(char type,char *source,int length,char **dest ,int length_dst,char just,short fill,char *pattern);
extern int comm_from_ascii(char *start_ptr,char type,int length,char *pattern);
extern int comm_to_bcd(char type,char *source,int length,char **dest ,int length_dst,char just,short fill,char *pattern);
extern int comm_from_bcd(char *start_ptr,char type,int length,char *pattern);
extern int comm_to_binary(char type,char *source,int length,char **dest ,int length_dst,char just,short fill,char *pattern);
static int convert_2_bin(char *ptr,char *end_ptr,unsigned char *bit_field,char *tmp_ascii,char sign_flag);
static int check_end(char **ptr ,char *end_ptr);
static int divide_by_2(char *ptr,char *end_ptr);
static void set_bit_field(unsigned char *ptr,short bit_number);
static void twos_complement(unsigned char *bit_field);
extern int comm_from_binary(char *start_ptr,char type,int length,char *pattern);
static char *convert_2_ascii(unsigned char *bit_field,char *ascii_num,char type);
static void multiply_by_2(char *ptr,char *end_ptr);
static int test_bit_field(unsigned char *ptr,int bit_number);
static void add_one(char *ptr,char *end_ptr);
static int con(char *pattern,char *data_bin,int data_bin_size);
extern int comm_to_bulk(char type,char *source,int length,char **dest ,int length_dst,char just,short fill,char *pattern);
extern int comm_from_bulk(char *start_ptr,char type,int length,char *pattern);
extern int comm_to_ebcdic(char type,char *source,int length,char **dest ,int length_dst,char just,short fill,char *pattern);
extern int comm_from_ebcdic(char *start_ptr,char type,int length,char *pattern);
extern int comm_to_flag(char type,char *source,int length,char **dest ,int length_dst,char just,short fill,char *pattern);
extern int comm_from_flag(char *start_ptr,char type,int length,char *pattern);
extern int comm_to_sebc(char type,char *source,int length,char **dest ,int length_dst,char just,short fill,char *pattern);
extern int comm_from_sebc(char *start_ptr,char type,int length,char *pattern);
extern int comm_to_user(char type,char *source,int length,char **dest ,int length_dst,char just,short fill,char *pattern);
extern int comm_from_user(char *start_ptr,char type,int length,char *pattern);
extern int comm_send_confirm(void);
extern int comm_send_comreq(unsigned short req,char *status);
extern int comm_allocate(char *dest,char *src);
extern int comm_deallocate(void);
extern int comm_log(char logon);
extern void comm_clear_timers(void);
extern void comm_set_timers(void);
extern void comm_output_timers(struct _iobuf *fptr);
extern int comm_send_data(char *dest,char confirm,char cat,char format,char msg_pos,char brkt);
extern void comm_dump_buff(void);
extern void comm_dump_buffer(char *dump_ptr,int byte_count);
static void put_byte(char *ptr,char value);
static void dump_ptrs(void);
extern int comm_setresource(char *resource,char init_type);
static struct RES_TCB *comm_selrcb(char *resource);
extern int comm_rcv(int event,void *ptr,char *buf,int len);
extern int comm_waitformsg(int timeout,int reset_timeout);
extern void comm_dispatch_events(void);
extern int comm_hold_events(void);
extern int comm_set_event(char *resource,struct PCLDEF *pcl_script);
static void comm_cfg_channel(struct RES_TCB *rcb);
extern void comm_cleanup(void);
extern int comm_get_de_edit(int argc,char **argv );
extern char *comm_get(char source,char type,int length,short delim,char *pattern,char *ltrim,char *rtrim,char *otrim);
extern char *comm_hdr(char token);
static void comm_hdr_func( void *cs, unsigned token );
extern int comm_init(void);
static void read_trans_table(char *file,char *table);
static int load_trans(void);
static void process_config(void);
extern void comm_init_buffers(struct RES_TCB *rcb);
static void set_pcl_variables(struct RES_TCB *rcb,struct CONFIG *node, struct hcomm_list *);
static char *comm_get_list_elem(unsigned char *fieldlist,short row,short col,char type);
static void init_crt(struct RES_TCB *rcb, struct CONFIG *cfg);
extern int comm_match(char start,char *pattern,char *comp_pat,char type,int length);
extern void comm_init_ptrs(struct RES_TCB *res,char type);
extern int comm_putptr(char *ptr,char ptr_token);
extern char *comm_getptr(char ptr_token);
extern int comm_putat(char ptr_token,char value);
extern int comm_getat(char ptr_token);
extern void comm_cpbuf(char **begin_ptr ,char **end_ptr ,char *buffer,int i);
extern int comm_put(char type,char *source,int length,char dest_token,int length_dst,char just,short fill,char *pattern,char *ltrim,char *rtrim,char *otrim);
extern int comm_ck_alloc(char **ptr );
extern int comm_ck_talloc(int length);
extern void comm_adj_ptrs(char *new_block,int i,int new_size);
extern char **comm_ptr(int token) ;
extern int comm_trim(char **str ,int *flength,char *trim_set,char type);
extern int comm_ck_rcv(struct RES_TCB *rcb,char *ptr);
static int send_cmd(void *cmd,int len);
extern int crt_buffer(short buf_oper);
extern int crt_cursor_abs(unsigned char row,unsigned char col);
extern int crt_cursor_rel(short positions);
extern int crt_fill(short fill_char,unsigned char row,unsigned char col,short length);
extern int crt_find_attribute(unsigned char row,unsigned char col,short length,unsigned long attribute);
extern int crt_field_abs(short field_number);
extern int crt_field_rel(short count);
extern int crt_get(unsigned char row,unsigned char col,short length,char *ltrim,char *rtrim,char *otrim, char **result);
extern int crt_kybd_status(void);
extern int crt_put(char type,char *source,unsigned char row,unsigned char col,short length,char *ltrim,char *rtrim,char *otrim);
extern int crt_put_buffer(char type,char *source,unsigned char row,unsigned char col,short length,char *ltrim,char *rtrim,char *otrim);
extern int crt_test_attribute(unsigned char row,unsigned char col,unsigned long attribute);
extern int crt_match(unsigned char row,unsigned char col,short length,char *pat,char *comp_pat);
extern int crt_set_mode(short win,short mode);
extern int crt_set_window(short win);
extern int crt_get_cursor(void);
extern int crt_check(void);
extern void comm_errmsg( char *,... );
extern int comm_init_lua(void);
extern int comm_init_cpic(void);
extern int comm_init_ctc(void);
extern int comm_init_x25(void);
extern int comm_init_pplus(void);
extern void comm_load_xlate();
struct RES_TCB *comm_create_rcb( char *name, short comm_type );
extern long comm_run_event( struct RES_TCB *rcb, void **args, char *bp, int len, int offset );
void comm_save_env( struct RES_TCB *rcb );
void comm_restore_env( struct RES_TCB *rcb );
extern int comm_lua_send( unsigned msgtype, unsigned flags );
extern int comm_wait_msgque(void);
extern int comm_release_msgque(void);
extern int comm_event_active(void);
